// import "./js/modules_task/module-1.js"
// import "./js/modules_task/module-2.js"
// import "./js/modules_task/module-3.js"
// import "./js/example1.js"
// import "./js/example2.js"
// import "./js/example3.js"
// import "./js/example4.js"
// import "./js/example4.1.js"
// import "./js/example4.2.js"
// import "./js/example5.js"
// import "./js/example6.js"
// import "./js/example7.js"
// import "./js/example8.js"
import "./js/example9.js"
import "./js/lessons_task/modul.1-lesson.1.js"
import "./js/modul.1-lesson.2.js"
import "./js/modul.2-lesson.1.js"
import "./js/modul.2-lesson.2.js"
import "./js/modul.3-lesson.1.js"
import "./js/modul.3-lesson.2.js"
import "./js/modul.4-lesson.1.js"
import "./js/modul.4-lesson.2.js"
import "./js/modul.5-lesson.1.js"
import "./js/modul.5-lesson.2.js"